using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Native.Mcp.SourceGenerator.Internal;

namespace Native.Mcp.SourceGenerator;

/// <summary>
/// Discovers types implementing <c>Native.Mcp.IMcpTool&lt;TInput, TOutput&gt;</c> and, for each,
/// emits a partial declaration exposing a generated <c>InputSchemaJson</c> (JSON Schema Draft
/// 2020-12 derived from <c>TInput</c>). Also emits an assembly-wide
/// <c>AddDiscoveredTools(this McpServerOptions, JsonSerializerContext)</c> helper.
/// </summary>
[Generator]
public sealed class InputSchemaGenerator : IIncrementalGenerator
{
    private const string ToolInterfaceMetadataName = "IMcpTool`2";
    private const string ToolInterfaceNamespace = "Native.Mcp";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var tools = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax { BaseList: not null },
                transform: static (ctx, ct) => GetToolModel(ctx, ct))
            .Where(static model => model is not null)
            .Select(static (model, _) => model!);

        context.RegisterSourceOutput(tools, static (spc, model) => EmitToolPartial(spc, model));

        var collected = tools.Collect();
        context.RegisterSourceOutput(collected, static (spc, models) => ToolDiscoveryGenerator.Emit(spc, models));
    }

    private static ToolModel? GetToolModel(GeneratorSyntaxContext context, System.Threading.CancellationToken ct)
    {
        var declaration = (TypeDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration, ct) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        var toolInterface = symbol.AllInterfaces.FirstOrDefault(static i =>
            i.MetadataName == ToolInterfaceMetadataName &&
            i.ContainingNamespace?.ToDisplayString() == ToolInterfaceNamespace);

        if (toolInterface is null || toolInterface.TypeArguments.Length != 2)
        {
            return null;
        }

        var inputType = toolInterface.TypeArguments[0];
        var outputType = toolInterface.TypeArguments[1];

        var schemaJson = inputType is INamedTypeSymbol namedInput
            ? TypeToJsonSchemaMapper.Build(namedInput)
            : null;

        var isPartial = declaration.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword));
        var canEmitPartial = isPartial
            && symbol.ContainingType is null
            && !symbol.IsGenericType
            && schemaJson is not null;

        return new ToolModel(
            ToolFqn: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            InputFqn: inputType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            OutputFqn: outputType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Namespace: symbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : symbol.ContainingNamespace.ToDisplayString(),
            TypeName: symbol.Name,
            TypeKeyword: ResolveTypeKeyword(symbol),
            AccessibilityKeyword: ResolveAccessibility(symbol.DeclaredAccessibility),
            SchemaJson: schemaJson ?? string.Empty,
            CanEmitPartial: canEmitPartial);
    }

    private static void EmitToolPartial(SourceProductionContext context, ToolModel model)
    {
        if (!model.CanEmitPartial)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        var indent = hasNamespace ? "    " : string.Empty;
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        sb.Append(indent).Append(model.AccessibilityKeyword).Append(" partial ")
            .Append(model.TypeKeyword).Append(' ').Append(model.TypeName).AppendLine();
        sb.Append(indent).AppendLine("{");

        sb.Append(indent).AppendLine("    /// <summary>Generated JSON Schema (Draft 2020-12) for this tool's input.</summary>");
        sb.Append(indent).AppendLine("    public static string InputSchemaJson =>");

        var literalIndent = indent + "        ";
        sb.Append(literalIndent).AppendLine("\"\"\"");
        foreach (var line in model.SchemaJson.Split('\n'))
        {
            sb.Append(literalIndent).AppendLine(line.TrimEnd('\r'));
        }

        sb.Append(literalIndent).AppendLine("\"\"\";");

        sb.Append(indent).AppendLine("}");
        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        var hintName = (string.IsNullOrEmpty(model.Namespace) ? string.Empty : model.Namespace + ".")
            + model.TypeName + ".InputSchema.g.cs";
        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string ResolveTypeKeyword(INamedTypeSymbol symbol)
    {
        if (symbol.IsRecord)
        {
            return symbol.TypeKind == TypeKind.Struct ? "record struct" : "record";
        }

        return symbol.TypeKind == TypeKind.Struct ? "struct" : "class";
    }

    private static string ResolveAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.ProtectedAndInternal => "private protected",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        Accessibility.Private => "private",
        _ => "internal",
    };
}

/// <summary>Immutable, equatable model of a discovered tool (drives incremental caching).</summary>
/// <param name="ToolFqn">Fully-qualified tool type name (with <c>global::</c>).</param>
/// <param name="InputFqn">Fully-qualified input type name.</param>
/// <param name="OutputFqn">Fully-qualified output type name.</param>
/// <param name="Namespace">The tool's namespace (empty for global).</param>
/// <param name="TypeName">The tool's simple type name.</param>
/// <param name="TypeKeyword">The declaration keyword (class/record/...).</param>
/// <param name="AccessibilityKeyword">The accessibility modifier.</param>
/// <param name="SchemaJson">The generated input schema (empty if not derivable).</param>
/// <param name="CanEmitPartial">Whether a partial member can be emitted for the type.</param>
internal sealed record ToolModel(
    string ToolFqn,
    string InputFqn,
    string OutputFqn,
    string Namespace,
    string TypeName,
    string TypeKeyword,
    string AccessibilityKeyword,
    string SchemaJson,
    bool CanEmitPartial);
