using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Native.Mcp.SourceGenerator;

/// <summary>
/// Emits the assembly-wide <c>AddDiscoveredTools(this McpServerOptions, JsonSerializerContext)</c>
/// extension that registers every discovered tool. This is the AOT-safe, opt-in alternative to
/// explicit <c>options.AddTool&lt;...&gt;()</c> calls — the consumer's serializer context must
/// declare each tool's input/output types.
/// </summary>
internal static class ToolDiscoveryGenerator
{
    public static void Emit(SourceProductionContext context, ImmutableArray<ToolModel> models)
    {
        if (models.IsDefaultOrEmpty)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Native.Mcp");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Generated registration helpers for tools discovered in this assembly.</summary>");
        sb.AppendLine("    public static class McpDiscoveredToolsExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers every <c>IMcpTool</c> discovered in this assembly using the supplied");
        sb.AppendLine("        /// serializer context for input/output type info. AOT-safe.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::Native.Mcp.McpServerOptions AddDiscoveredTools(");
        sb.AppendLine("            this global::Native.Mcp.McpServerOptions options,");
        sb.AppendLine("            global::System.Text.Json.Serialization.JsonSerializerContext context)");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.Append("            options.AddTool<")
                .Append(model.ToolFqn).Append(", ")
                .Append(model.InputFqn).Append(", ")
                .Append(model.OutputFqn).AppendLine(">(context);");
        }

        sb.AppendLine("            return options;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("McpDiscoveredToolsExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
